<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AssemblyName>Notifications.Core</AssemblyName>
    <RootNamespace>Notifications.Core</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Abstractions" Version="9.0.5" />
  </ItemGroup>
</Project>
