<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AssemblyName>Notifications.Consumer</AssemblyName>
    <RootNamespace>Notifications.Consumer</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Notifications.Core\Notifications.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="App.config" />
    <Content Include="Data\Customer.csv" />
    <Content Include="Data\Output\placeholder.txt" />
    <Content Include="Data\renewal_template.txt" />
  </ItemGroup>
</Project>
